Move hardcoded URLS to environment.ts
BPChain/angular-frontend pull request #5
Opened 2017-12-12 15:12 UTC by bisbaldi

2017-12-12 18:01 UTC, fyndalf requested changes
I've added some comments - after the changes have been made, this will look good to me :)

2017-12-12 18:01 UTC, fyndalf commented on src/app/app.module.ts
> +import {NgModule} from '@angular/core';
Fix spacing between import argument to be like { someModule }

2017-12-12 18:01 UTC, fyndalf commented on src/app/services/private-stats.service.ts
> +import {environment} from '../../environments/environment';
Fix spacing

2017-12-12 18:01 UTC, fyndalf commented on src/app/services/public-stats.service.ts
> +import {environment} from '../../environments/environment';
Also fix spacing here

2017-12-12 18:01 UTC, fyndalf commented on src/styles.css
> +}
Insert trailing newline

2017-12-13 10:03 UTC, svitlanakalancha approved these changes

2017-12-13 10:12 UTC, fyndalf approved these changes

2017-12-13 10:17 UTC, merged